// Shared data shapes. Persisted shapes mirror src/main/settings.js; event
// shapes mirror src/main/claude.js.

export interface Usage {
  input: number;
  output: number;
  cacheRead: number;
  cacheCreate: number;
}

export type MapId = 'forest' | 'desert' | 'snowy' | 'lava' | 'night';
export type PermissionMode = 'default' | 'acceptEdits' | 'plan' | 'bypassPermissions';
export type Theme = 'dark' | 'light';
export type ModelAlias = 'opus' | 'sonnet' | 'haiku';
/** Where the archive drawer sits: left or right of the chat panel (the window widens), or over it when there is no room. */
export type DrawerMode = 'left' | 'right' | 'overlay';
/** A chat entry. Tool calls carry a name/summary, everything else text. */
export type ChatMessage =
  | { kind: 'tool'; name: string; summary?: string }
  | { kind: 'user' | 'assistant' | 'error' | 'meta' | 'thinking'; text: string };

/** Something that can follow a "/" in the chat: an agent, a skill, a custom command, or a built-in Claude Code command. */
export interface CommandEntry {
  name: string;
  kind: 'agent' | 'skill' | 'command' | 'builtin';
  /** Where it comes from: "project", "user", "claude.ai sync", "built in"... */
  source: string;
  description: string;
  argumentHint: string;
}

/** An agent a project can invoke with "/<name>": a markdown file under .claude/agents/. */
export interface AgentDefinition {
  name: string;
  description: string;
  source: 'project' | 'user';
}

export interface AgentRecord {
  id: string;
  name: string;
  status: string;
}

/** A retired or closed agent's chat, kept per project (main/archive.js clamps and validates it). Read-only. */
export interface ArchivedAgent {
  /** The agent id ("observed-<toolUseId>" for delegated ones); a repeat replaces the older entry. */
  id: string;
  name: string;
  definition: string;
  /** The first message sent to the agent. */
  task: string;
  observed: boolean;
  status: 'done' | 'error' | 'cancelled';
  /** idle = retired after the idle time; closed = its tab was closed. */
  reason: 'idle' | 'closed';
  startedAt: number;
  endedAt: number | null;
  /** Set by the main process. */
  archivedAt: number;
  usage: Usage;
  /** Kept for a future "resume"; nothing uses it yet. */
  sessionId: string | null;
  messages: ChatMessage[];
}

export interface Workspace {
  id: string;
  path: string;
  name: string;
  heroSeed: string;
  /** Look of a summoned hero, designed by Claude and validated in the main process (null: generated from the seed). */
  heroDesign?: HeroDesign | null;
  usage: Usage;
  lastContext: number;
  contextWindow: number;
  kills: number;
  map: MapId;
  sessionId: string | null;
  messages: ChatMessage[];
  agents: AgentRecord[];
  /** Chats of retired / closed agents, newest last. Changed only through the archive handlers in main. */
  archive: ArchivedAgent[];
  /** Map bosses defeated, by boss id ("boss:forest"). */
  trophies: Record<string, { count: number; firstAt: number }>;
  /** Earned achievements by id (main allowlists the ids). Never removed once earned. */
  achievements: Record<string, { at: number }>;
  /** Lifetime counters the achievements read (main clamps what the renderer reports). */
  stats: WorkspaceStats;
}

export interface WorkspaceStats {
  bestCombo: number;
  crits: number;
  agents: number;
  mapsSeen: string[];
}

export interface Settings {
  permissionMode: PermissionMode;
  windowPos: { x: number; y: number } | null;
  workspaces: Workspace[];
  activeId: string | null;
  theme: Theme;
  panelHeight: number;
  /** One-time data migrations applied by the main process (read-only here). */
  migrations?: Record<string, boolean>;
}

/** A validated hero design (main/hero-design.js) plus the time it was saved. */
export interface HeroDesign {
  cls: string;
  weapon: string;
  body: string;
  gear: string;
  hair: string;
  shield: boolean;
  cape: boolean;
  stache: boolean;
  glasses: boolean;
  colors: Record<string, string>;
  stats: { hp: number; atk: number; def: number; spd: number };
  signatureGlow?: string;
  at: number;
}

/** Generated by engine/heroes.js from a workspace's seed. */
export interface Hero {
  seed: string;
  name: string;
  classId: string;
  cls: string;
  weapon: string;
  colors: { armor?: string; [key: string]: string | undefined };
  stats: { hp: number; atk: number; def: number; spd: number };
  [key: string]: unknown;
}

/** One entry of the map list. */
export interface Background {
  id: MapId;
  name: string;
}

// ----- Events streamed from the main process -----

export interface ClaudeEvent {
  type: 'start' | 'session' | 'turn' | 'usage' | 'thinking' | 'text' | 'tool' | 'subagent' | 'result' | 'error' | 'end';
  wsId?: string;
  sessionId?: string;
  text?: string;
  name?: string;
  summary?: string;
  message?: string;
  isError?: boolean;
  costUsd?: number;
  turns?: number;
  durationMs?: number;
  contextWindow?: number | null;
  /** Exit code on 'end' (non-zero or null when the process failed or was cancelled). */
  code?: number | null;
  /** Tokens of one model call: a snapshot on 'turn', the final count on 'usage'. */
  usage?: Usage;
  /** Workspace lifetime totals, attached to 'usage' events. */
  totals?: Usage;
  lastContext?: number;
  /**
   * 'subagent' = Claude delegated to one of its agents through its Agent tool. `toolUseId` is that call's id:
   * 'start' carries agentType/description/prompt, 'event' one thing the subagent did (`inner` = 'tool' with
   * name/summary, or 'text' with text), 'end' its result (text, isError).
   */
  phase?: 'start' | 'event' | 'end';
  toolUseId?: string;
  agentType?: string;
  description?: string;
  prompt?: string;
  inner?: 'tool' | 'text';
}

export interface AgentEvent extends ClaudeEvent {
  agentId: string;
}

// ----- Preload bridge (window.bar) -----

export type Unsubscribe = () => void;

export interface Bar {
  getSettings(): Promise<Settings>;
  setSettings(patch: Partial<Settings>): Promise<Settings>;
  updateSettings(patch: Partial<Settings>): Promise<Settings>;
  importWorkspace(): Promise<Settings | null>;
  selectWorkspace(id: string): Promise<Settings>;
  removeWorkspace(id: string): Promise<Settings>;
  /** Random new hero, or a secret hero when `seed` is one of the allowed secret seeds. */
  rerollHero(id: string, seed?: string): Promise<Settings>;
  /** Asks Claude (in main, no tools) to design the look of a summoned name; main validates and saves it. */
  designSummon(wsId: string, name: string): Promise<{ ok: true; cached?: boolean; settings: Settings } | { ok: false; reason: string }>;
  updateWorkspace(id: string, patch: Partial<Pick<Workspace, 'kills' | 'map'>>): Promise<Settings>;
  /** A map boss was defeated: adds it to the workspace's trophies (main validates the boss id). */
  addTrophy(id: string, bossId: string): Promise<Settings>;
  /** An achievement was earned (main validates the id; a repeat is ignored). */
  addAchievement(id: string, achId: string): Promise<Settings>;
  /** Counter changes since the last flush: `crits` and `agents` are added, `bestCombo` is a max, `mapsSeen` is merged. */
  addStats(id: string, delta: Partial<WorkspaceStats>): Promise<Settings>;
  /** The silent first-load unlock of already-earned achievements is done (sets the migration flag). */
  achievementsBackfilled(): Promise<Settings>;

  setClickThrough(ignore: boolean): void;
  focus(): void;
  dragStart(): void;
  dragEnd(): void;
  panelSide(): Promise<'above' | 'below'>;
  setPanelOpen(open: boolean): Promise<'above' | 'below'>;
  /** Where the archive drawer would open for the strip's current spot. */
  drawerMode(): Promise<DrawerMode>;
  /** Ask main to open or close the drawer (it chooses the mode and the window size). 'none' = closed or refused. */
  setDrawerOpen(open: boolean): Promise<DrawerMode | 'none'>;
  quit(): void;
  restartApp(): void;

  send(prompt: string, model: ModelAlias): void;
  cancel(): void;
  newSession(): Promise<Settings>;
  info(): Promise<{ bin: string }>;

  sendGeneralChat(prompt: string, model: ModelAlias): void;
  cancelGeneralChat(): void;

  /** Everything the "/" popup offers for this project: agents, skills and custom commands. */
  commandCatalog(wsId: string): Promise<CommandEntry[]>;
  /** Agents defined under .claude/agents/ for this project (and the user's own). */
  agentDefinitions(wsId: string): Promise<AgentDefinition[]>;
  /** Runs one agent in its own process; `error` is set when it could not start. */
  runAgent(
    wsId: string, definitionName: string, displayName: string, task: string, permissionMode: PermissionMode,
  ): Promise<{ agent?: AgentRecord; definitionName?: string; error?: string }>;
  messageAgent(
    wsId: string, agentId: string, sessionId: string, definitionName: string, prompt: string, cwd: string,
    permissionMode: PermissionMode,
  ): void;
  /** Whether the project has .claude/review.md (the path comes from the workspace). */
  projectHasReview(wsId: string): Promise<boolean>;
  cancelAgent(wsId: string, agentId: string): Promise<Settings | null>;
  listAgents(wsId: string): Promise<AgentRecord[]>;
  /** Stores a retired / closed agent's chat in the project's archive (main clamps it; null = refused). */
  archiveAgent(wsId: string, record: Omit<ArchivedAgent, 'archivedAt'>): Promise<{ archive: ArchivedAgent[] } | null>;
  deleteArchived(wsId: string, id: string): Promise<{ archive: ArchivedAgent[] } | null>;
  clearArchive(wsId: string): Promise<{ archive: ArchivedAgent[] } | null>;

  onClaudeEvent(cb: (event: ClaudeEvent) => void): Unsubscribe;
  onAgentEvent(cb: (event: AgentEvent) => void): Unsubscribe;
  onGeneralChatEvent(cb: (event: ClaudeEvent) => void): Unsubscribe;
  onTogglePanel(cb: () => void): Unsubscribe;
  onPanelSide(cb: (side: 'above' | 'below') => void): Unsubscribe;
  onDrawerMode(cb: (mode: DrawerMode) => void): Unsubscribe;
  addMessage(wsId: string, message: ChatMessage): void;
}

declare global {
  interface Window {
    bar: Bar;
  }
}
