// Shared data shapes. Persisted shapes mirror src/main/settings.js; event
// shapes mirror src/main/claude.js.

export interface Usage {
  input: number;
  output: number;
  cacheRead: number;
  cacheCreate: number;
}

export type MapId = 'forest' | 'desert' | 'snowy' | 'lava' | 'night';
export type PermissionMode = 'default' | 'acceptEdits' | 'plan' | 'bypassPermissions';
export type Theme = 'dark' | 'light';
export type ModelAlias = 'opus' | 'sonnet' | 'haiku';

/** A chat entry. Tool calls carry a name/summary, everything else text. */
export type ChatMessage =
  | { kind: 'tool'; name: string; summary?: string }
  | { kind: 'user' | 'assistant' | 'error' | 'meta' | 'thinking'; text: string };

export interface AgentRecord {
  id: string;
  name: string;
  status: string;
}

export interface Workspace {
  id: string;
  path: string;
  name: string;
  heroSeed: string;
  usage: Usage;
  lastContext: number;
  contextWindow: number;
  kills: number;
  map: MapId;
  sessionId: string | null;
  messages: ChatMessage[];
  agents: AgentRecord[];
}

export interface Settings {
  permissionMode: PermissionMode;
  windowPos: { x: number; y: number } | null;
  workspaces: Workspace[];
  activeId: string | null;
  theme: Theme;
  panelHeight: number;
}

/** Generated by engine/heroes.js from a workspace's seed. */
export interface Hero {
  seed: string;
  name: string;
  classId: string;
  cls: string;
  weapon: string;
  colors: { armor?: string; [key: string]: string | undefined };
  stats: { hp: number; atk: number; def: number; spd: number };
  [key: string]: unknown;
}

/** One entry of the map list. */
export interface Background {
  id: MapId;
  name: string;
}

// ----- Events streamed from the main process -----

export interface ClaudeEvent {
  type: 'start' | 'session' | 'turn' | 'usage' | 'thinking' | 'text' | 'tool' | 'result' | 'error' | 'end';
  wsId?: string;
  sessionId?: string;
  text?: string;
  name?: string;
  summary?: string;
  message?: string;
  isError?: boolean;
  costUsd?: number;
  turns?: number;
  durationMs?: number;
  contextWindow?: number | null;
  /** Tokens of one model call: a snapshot on 'turn', the final count on 'usage'. */
  usage?: Usage;
  /** Workspace lifetime totals, attached to 'usage' events. */
  totals?: Usage;
  lastContext?: number;
}

export interface AgentEvent extends ClaudeEvent {
  agentId: string;
}

// ----- Preload bridge (window.bar) -----

export type Unsubscribe = () => void;

export interface Bar {
  getSettings(): Promise<Settings>;
  setSettings(patch: Partial<Settings>): Promise<Settings>;
  updateSettings(patch: Partial<Settings>): Promise<Settings>;
  importWorkspace(): Promise<Settings | null>;
  selectWorkspace(id: string): Promise<Settings>;
  removeWorkspace(id: string): Promise<Settings>;
  /** Random new hero, or a secret hero when `seed` is one of the allowed secret seeds. */
  rerollHero(id: string, seed?: string): Promise<Settings>;
  updateWorkspace(id: string, patch: Partial<Pick<Workspace, 'kills' | 'map'>>): Promise<Settings>;

  setClickThrough(ignore: boolean): void;
  focus(): void;
  dragStart(): void;
  dragEnd(): void;
  panelSide(): Promise<'above' | 'below'>;
  setPanelOpen(open: boolean): Promise<'above' | 'below'>;
  quit(): void;
  restartApp(): void;

  send(prompt: string, model: ModelAlias): void;
  cancel(): void;
  newSession(): Promise<Settings>;
  info(): Promise<{ bin: string }>;

  sendGeneralChat(prompt: string, model: ModelAlias): void;
  cancelGeneralChat(): void;

  spawnAgents(
    wsId: string, count: number, prompt: string, cwd: string, permissionMode: PermissionMode,
  ): Promise<AgentRecord[] | null>;
  messageAgent(
    wsId: string, agentId: string, sessionId: string, prompt: string, cwd: string, permissionMode: PermissionMode,
  ): void;
  cancelAgent(wsId: string, agentId: string): Promise<Settings | null>;
  listAgents(wsId: string): Promise<AgentRecord[]>;

  onClaudeEvent(cb: (event: ClaudeEvent) => void): Unsubscribe;
  onAgentEvent(cb: (event: AgentEvent) => void): Unsubscribe;
  onGeneralChatEvent(cb: (event: ClaudeEvent) => void): Unsubscribe;
  onTogglePanel(cb: () => void): Unsubscribe;
  onPanelSide(cb: (side: 'above' | 'below') => void): Unsubscribe;
  addMessage(wsId: string, message: ChatMessage): void;
}

declare global {
  interface Window {
    bar: Bar;
  }
}
