// Shared data shapes. Persisted shapes mirror src/main/settings.js; event
// shapes mirror src/main/claude.js.

export interface Usage {
  input: number;
  output: number;
  cacheRead: number;
  cacheCreate: number;
}

export type MapId = 'forest' | 'desert' | 'snowy' | 'lava' | 'night';
export type PermissionMode = 'default' | 'acceptEdits' | 'plan' | 'bypassPermissions';
export type Theme = 'dark' | 'light';
export type ModelAlias = 'opus' | 'sonnet' | 'haiku';

/** A chat entry. Tool calls carry a name/summary, everything else text. */
export type ChatMessage =
  | { kind: 'tool'; name: string; summary?: string }
  | { kind: 'user' | 'assistant' | 'error' | 'meta' | 'thinking'; text: string };

/** Something that can follow a "/" in the chat: an agent, a skill, a custom command, or a built-in Claude Code command. */
export interface CommandEntry {
  name: string;
  kind: 'agent' | 'skill' | 'command' | 'builtin';
  /** Where it comes from: "project", "user", "claude.ai sync", "built in"... */
  source: string;
  description: string;
  argumentHint: string;
}

/** An agent a project can invoke with "/<name>": a markdown file under .claude/agents/. */
export interface AgentDefinition {
  name: string;
  description: string;
  source: 'project' | 'user';
}

export interface AgentRecord {
  id: string;
  name: string;
  status: string;
}

export interface Workspace {
  id: string;
  path: string;
  name: string;
  heroSeed: string;
  usage: Usage;
  lastContext: number;
  contextWindow: number;
  kills: number;
  map: MapId;
  sessionId: string | null;
  messages: ChatMessage[];
  agents: AgentRecord[];
}

export interface Settings {
  permissionMode: PermissionMode;
  windowPos: { x: number; y: number } | null;
  workspaces: Workspace[];
  activeId: string | null;
  theme: Theme;
  panelHeight: number;
}

/** Generated by engine/heroes.js from a workspace's seed. */
export interface Hero {
  seed: string;
  name: string;
  classId: string;
  cls: string;
  weapon: string;
  colors: { armor?: string; [key: string]: string | undefined };
  stats: { hp: number; atk: number; def: number; spd: number };
  [key: string]: unknown;
}

/** One entry of the map list. */
export interface Background {
  id: MapId;
  name: string;
}

// ----- Events streamed from the main process -----

export interface ClaudeEvent {
  type: 'start' | 'session' | 'turn' | 'usage' | 'thinking' | 'text' | 'tool' | 'subagent' | 'result' | 'error' | 'end';
  wsId?: string;
  sessionId?: string;
  text?: string;
  name?: string;
  summary?: string;
  message?: string;
  isError?: boolean;
  costUsd?: number;
  turns?: number;
  durationMs?: number;
  contextWindow?: number | null;
  /** Exit code on 'end' (non-zero or null when the process failed or was cancelled). */
  code?: number | null;
  /** Tokens of one model call: a snapshot on 'turn', the final count on 'usage'. */
  usage?: Usage;
  /** Workspace lifetime totals, attached to 'usage' events. */
  totals?: Usage;
  lastContext?: number;
  /**
   * 'subagent' = Claude delegated to one of its agents through its Agent tool. `toolUseId` is that call's id:
   * 'start' carries agentType/description/prompt, 'event' one thing the subagent did (`inner` = 'tool' with
   * name/summary, or 'text' with text), 'end' its result (text, isError).
   */
  phase?: 'start' | 'event' | 'end';
  toolUseId?: string;
  agentType?: string;
  description?: string;
  prompt?: string;
  inner?: 'tool' | 'text';
}

export interface AgentEvent extends ClaudeEvent {
  agentId: string;
}

// ----- Preload bridge (window.bar) -----

export type Unsubscribe = () => void;

export interface Bar {
  getSettings(): Promise<Settings>;
  setSettings(patch: Partial<Settings>): Promise<Settings>;
  updateSettings(patch: Partial<Settings>): Promise<Settings>;
  importWorkspace(): Promise<Settings | null>;
  selectWorkspace(id: string): Promise<Settings>;
  removeWorkspace(id: string): Promise<Settings>;
  /** Random new hero, or a secret hero when `seed` is one of the allowed secret seeds. */
  rerollHero(id: string, seed?: string): Promise<Settings>;
  updateWorkspace(id: string, patch: Partial<Pick<Workspace, 'kills' | 'map'>>): Promise<Settings>;

  setClickThrough(ignore: boolean): void;
  focus(): void;
  dragStart(): void;
  dragEnd(): void;
  panelSide(): Promise<'above' | 'below'>;
  setPanelOpen(open: boolean): Promise<'above' | 'below'>;
  quit(): void;
  restartApp(): void;

  send(prompt: string, model: ModelAlias): void;
  cancel(): void;
  newSession(): Promise<Settings>;
  info(): Promise<{ bin: string }>;

  sendGeneralChat(prompt: string, model: ModelAlias): void;
  cancelGeneralChat(): void;

  /** Everything the "/" popup offers for this project: agents, skills and custom commands. */
  commandCatalog(wsId: string): Promise<CommandEntry[]>;
  /** Agents defined under .claude/agents/ for this project (and the user's own). */
  agentDefinitions(wsId: string): Promise<AgentDefinition[]>;
  /** Runs one agent in its own process; `error` is set when it could not start. */
  runAgent(
    wsId: string, definitionName: string, displayName: string, task: string, permissionMode: PermissionMode,
  ): Promise<{ agent?: AgentRecord; definitionName?: string; error?: string }>;
  messageAgent(
    wsId: string, agentId: string, sessionId: string, definitionName: string, prompt: string, cwd: string,
    permissionMode: PermissionMode,
  ): void;
  /** Whether the project has .claude/review.md (the path comes from the workspace). */
  projectHasReview(wsId: string): Promise<boolean>;
  cancelAgent(wsId: string, agentId: string): Promise<Settings | null>;
  listAgents(wsId: string): Promise<AgentRecord[]>;

  onClaudeEvent(cb: (event: ClaudeEvent) => void): Unsubscribe;
  onAgentEvent(cb: (event: AgentEvent) => void): Unsubscribe;
  onGeneralChatEvent(cb: (event: ClaudeEvent) => void): Unsubscribe;
  onTogglePanel(cb: () => void): Unsubscribe;
  onPanelSide(cb: (side: 'above' | 'below') => void): Unsubscribe;
  addMessage(wsId: string, message: ChatMessage): void;
}

declare global {
  interface Window {
    bar: Bar;
  }
}
